name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]  # Make sure this is the exact name of your CI workflow
    types:
      - completed

jobs:
  build:
    if: github.event.workflow_run.conclusion == 'success'  # Ensure CI completed successfully
    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull marufp10/cicd-pipeline:latest
    - name: Delete Old docker container
      run: sudo docker rm -f cicd-pipeline-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8080:8080 --name cicd-pipeline-container marufp10/cicd-pipeline